default: 15
items:
    "Big Grin": 100
    "Blackout Kilt": 100
    "Blackout Pants": 100
    "Blackout Hoodie": 100
    "Blackout Jacket": 100
    "No Mercy Hoodie": 100
    "No Mercy Pants": 100
    "Gold Rock": 100
    "Yellow Police": 100
    "Tempered AK47": 100
    "Neon Sign Pack": 100
    "High Voltage": 100
    "Rust Island Car Rug": 100
    "Metalhead M39": 100
    "Polymer LR300": 100
    "Batteries Not Included MP5": 100
    "Flower hat": 100
    "Tailor's Carpet": 100
    "No Mercy Mp5": 100
    "Glory Thompson": 100
    "Surgeons Scrubs": 100
    "Neon Pumpkin": 100
    "Large Fireworks Pack": 100
    "Glacial Visage": 100
    "Neon Ore Storage": 100
    "Dragon Horn Box": 100
    "Whiteout Hoodie": 100
    "Whiteout Kilt": 100
    "Whiteout Pants": 100
    "Whiteout Jacket": 100
    "Whiteout Facemask": 100
    "Whiteout Roadsign": 100
    "Whiteout Chestplate": 100
    "Tempered Bow": 100
